In [65]:
import pandas as pd

# Load the dataset
df = pd.read_csv('dataset_Facebook.csv', sep=';')
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

### a. Create data subsets

In [66]:
# Creating two subsets
subset1 = df[['Type', 'Category', 'Post Month']].loc[:10]
subset2 = df[['Type', 'Total Interactions']].loc[:10]

display(subset1.head())
display(subset2.head())

     Type  Category  Post Month
0   Photo         2          12
1  Status         2          12
2   Photo         3          12
3   Photo         2          12
4   Photo         2          12

     Type  Total Interactions
0   Photo                 100
1  Status                 164
2   Photo                  80
3   Photo                1777
4   Photo                 393

### b. Merge Data

In [67]:
# Merging the two subsets on 'Type'
merged_df = pd.merge(subset1, subset2, on='Type')
merged_df

      Type  Category  Post Month  Total Interactions
0    Photo         2          12                 100
1    Photo         2          12                  80
2    Photo         2          12                1777
3    Photo         2          12                 393
4    Photo         2          12                 279
..     ...       ...         ...                 ...
60   Photo         3          12                 142
61  Status         2          12                 164
62  Status         2          12                 186
63  Status         2          12                 192
64  Status         2          12                 252

[65 rows x 4 columns]

### c. Sort Data

In [68]:
# Sorting the merged dataframe by 'Total Interactions'
sorted_df = merged_df.sort_values(by='Total Interactions', ascending=False)
sorted_df.head()

     Type  Category  Post Month  Total Interactions
2   Photo         2          12                1777
45  Photo         3          12                1777
13  Photo         3          12                1777
27  Photo         2          12                1777
20  Photo         2          12                1777

### d. Transposing Data

In [69]:
# Transposing the sorted dataframe
transposed_df = sorted_df.transpose()
transposed_df

,2,45,13,27,20,38,56,46,21,14,...,25,43,54,19,1,12,26,37,44,55
Type,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,...,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,3,3,2,2,3,3,3,2,3,...,2,3,3,2,2,3,2,3,3,3
Post Month,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,12
Total Interactions,1777,1777,1777,1777,1777,1777,1777,393,393,393,...,100,100,100,80,80,80,80,80,80,80

### e. Shape and reshape Data

In [70]:
# Shaping (finding dimensions)
print('Shape of dataframe:', subset1.shape)

# Reshaping (using melt to change from wide to long format)
reshaped_df = pd.melt(subset1, id_vars=['Type'], value_vars=['Category', 'Post Month'])
reshaped_df.head()

Shape of dataframe: (11, 3)

     Type  variable  value
0   Photo  Category      2
1  Status  Category      2
2   Photo  Category      3
3   Photo  Category      2
4   Photo  Category      2